import axios from 'axios'

const config = {
  baseUrl: 'http://192.168.86.36/api/',
  
  headers: {
    Cookie: 'turbo_auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhdGxhcy5jb20iLCJzaGFyZWQiOmZhbHNlLCJ0aXRsZSI6IiIsImxvY2FsZSI6ImVuLVVTIiwidGVuYW50LWlkIjo0LCJ0ZW5hbnQta2V5IjoiQVRMQVNDT1BDT0NSIiwiZXJwLWVuYWJsZWQiOmZhbHNlLCJzdXBlcmFkbWluIjpmYWxzZSwiZXhwIjoxNjA3NTk1MTgwLCJpYXQiOjE2MDc1NjYzODAsImp0aSI6ImZlYTk0ZjYyLTE5ZmUtNDc5NC05YmMzLWVmYTY2YjVlNjdmNiIsImVtYWlsIjoibWVsaXNzYS5icnVja25lckBkaWdhYml0LmNvbSIsImxvY2FsZS1pZCI6MSwibGFzdC1uYW1lIjoiYXRsYXMiLCJncm91cC1pZHMiOlszXSwidXNlci1pZCI6NCwiZmlyc3QtbmFtZSI6ImFkbWluIiwiZ2VuZXJpYyI6ZmFsc2UsIm9yZ2FuaXphdGlvbi1rZXkiOiJRdXdKcGsiLCJtZWRpYS1jYXRlZ29yeS1pZHMiOlsxMywxNCwxNV0sImF1ZCI6ImRldiIsInVzdDpyZWRpcmVjdCI6WyIvYWRtaW4vZGFzaGJvYXJkIl0sIm5iZiI6MTYwNzU2NjM4MCwicHJpdmlsZWdlLWlkcyI6WzAsMSwyLDMsNCw4LDksMTIsMTMsMTQsMTUsMTYsMjEsMjIsMjQsMjUsMjYsMjksMzAsMzMsMzQsMzUsMzYsMzcsMzgsMzksNDYsNDcsNDgsNDksNTEsNTQsNTUsNjAsNjEsNzZdLCJvcmdhbml6YXRpb24taWQiOjYsInVzZXJuYW1lIjoiYWRtaW5AYXRsYXMuY29tIn0.GJUvqDaq6UMVbKWhE2zuGRKRarijDxn9K9SF7r0Omao'
  }
}

const http = axios.create(config)

export default http;